- name: configure catalogue
  hosts: catalogue
  become: yes
  vars:
    MONGODB_HOST: mongodb-dev.sanjeethadevops.online

  tasks:

  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin

  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download catalogue
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip

  - name: extract catalogue
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: install node dependencies
    community.general.npm:
      path: /app

  - name: copy catalogue service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present

  - name: check catalogue db exists
    ansible.builtin.command: >
      mongosh --host "{{ MONGODB_HOST }}" --quiet
      --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: load catalogue schema
    ansible.builtin.shell: >
      mongosh --host "{{ MONGODB_HOST }}" < /app/schema/catalogue.js
    when: catalogue_output.stdout | int < 0

  - name: restart catalogue service
    ansible.builtin.systemd:
      name: catalogue
      state: restarted
      enabled: yes
      daemon_reload: yes