- name: catalogue configure
  hosts: catalogue
  become: yes
  tasks:
  - name: enable node js 20
    ansible.builtin.command: dnf module enable nodejs:20 -y 

  - name: Install node js
    ansible.builtin.dnf:
        name: nodejs
        state: present  

  - name: Create roboshop catalogue 
    ansible.builtin.catalogue :
        name: roboshop
        system: yes
        home: /app
        shell: /sbin/nologin
        comment: "roboshop system catalogue "
         

  - name: Create /app directory
    ansible.builtin.file:
        path: /app
        state: directory
       

  - name: Download catalogue application code
    ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip
       
  - name: Unzip catalogue code to /app
    ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

  - name: Install npm dependencies
    community.general.npm:
        path: /app   

  - name: Copy catalogue service file
    ansible.builtin.copy:
     src: catalogue.service
     dest: /etc/systemd/system/catalogue.service  

  - name: copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client 
    ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present       
 
  - name: check products loaded
    ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: print output
    ansible.builtin.debug:
     msg: "{{ catalogue_output }}"

  - name: Load catalogue schema
    ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" < /app/schema/catalogue.js 
    when: catalogue_output.stdout  | int < 0
 
  - name: Reload systemd
    ansible.builtin.systemd:
     daemon_reload: yes          

  - name: Enable and start catalogue
    ansible.builtin.service:
        name: catalogue
        enabled: yes
        state: started    