- name: redis configure
  hosts: localhost
  connection: local
  tasks:
   - name: enable redis
     ansible.builtin.command: dnf module enable redis:7 -y

   - name: Install redis 
     ansible.builtin.dnf:
        name: redis 
        state: present  

   - name: Replace bindIp in redis.conf
     ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0' 

   - name: Disable Redis protected mode
     ansible.builtin.lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^protected-mode'
        line: 'protected-mode no'
        state: present
        backup: yes     

   - name: start and enable redis
     ansible.builtin.service:
        name: redis
        enabled: yes
        state: started             