# ansible-playbook -i localhost -e {instrances=["mongodb","catalogue","redis","user","cart","mysql","shipping","rabbitmq","payment","frontend"]}
- name: create EC2 instance and route53 records
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
   sg_id: sg-0cbd13a547e558c9a
   ami_id: ami-0220d79f3f480ecf5
   domain_name: sanjeethadevops.online
   env: dev
   ec2_action: create
   instances:
     - catalogue
     - mongodb 
  tasks: 
  - name: EC2 instance creation
    amazon.aws.ec2_instance:
        instance_type: t3.micro
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"      
        name: "{{ item }}-{{ env }}"
        region: us-east-1
        tags:
          Project: roboshop
          component: "{{ item }}"
          Environment: "{{ env }}" 
          name: "{{ item }}-{{ env }}"

    loop: "{{ instances }}"
    register: ec2_output
    when: ec2_action == "create"

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

  - name: Create Route53 record
    amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item.item }}-{{ env }}.{{ domain_name }}"  #mangodb-dev.sanjeethadevops.online
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        overwrite: true
        wait: false
    loop: "{{ ec2_output.results }}"      
     
  - name: Create Route53 record
    amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "roboshop-{{ env }}.{{ domain_name }}"  #roboshop-dev.sanjeethadevops.online
        type: A
        ttl: 1
        value: "{{ item.instances[0].public_ip_address }}"
        overwrite: true
        wait: false
    loop: "{{ ec2_output.results }}"  
    when: 
    - item.item == "frontend"
    - ec2_action == "create"

    ### DESTROY ###
  - name: delete r53 records for frontend
    amazon.aws.route53:
      state: absent
      zone: "{{ domain_name }}"
      record: "roboshop-{{ env }}.{{ domain_name }}" # roboshop-dev.daws88s.online
      type: A
      ttl: 1
    loop: "{{ instances }}"
    when:  # and
    - item == "frontend"
    - action == "destroy"

  - name: delete r53 records
    amazon.aws.route53:
      state: absent
      zone: "{{ domain_name }}"
      record: "{{ item }}-{{ env }}.{{ domain_name }}" # roboshop-dev.daws88s.online
      type: A
      ttl: 1
    loop: "{{ instances }}"
    when: action == "destroy"

  - name: delete ec2 instance
    amazon.aws.ec2_instance:
      state: absent
      name: "{{ item }}-{{ env }}"
      wait: false
    loop: "{{ instances }}"
    when: action == "destroy"
